//
// Created by Danila on 15.02.2019.
//

#include "test.h"

TEST(SettingsCheck, FieldSettings) {
    ASSERT_EQ(TRUNCATION_FIELD_ERROR, 5);
    EXPECT_EQ(TRUNCATION_LIDAR_ERROR, 2);

    EXPECT_NEAR(MAX_FIELD_WIDTH, 2400, TRUNCATION_FIELD_ERROR);
    ASSERT_EQ(MAX_FIELD_HEIGHT, MAX_FIELD_WIDTH);

    EXPECT_NEAR(PARKING_ZONE_WIDTH_MAX, 380, TRUNCATION_FIELD_ERROR);
    EXPECT_NEAR(PARKING_ZONE_WIDTH_MIN, 360, TRUNCATION_FIELD_ERROR);

    EXPECT_NEAR(CLIMATE_BOX_WIDTH, 230, TRUNCATION_FIELD_ERROR);
    ASSERT_EQ(CLIMATE_BOX_WIDTH, CLIMATE_BOX_HEIGHT);

    EXPECT_NEAR(FLOWER_CUBE_WIDTH, 48, TRUNCATION_FIELD_ERROR);
    ASSERT_EQ(FLOWER_CUBE_WIDTH, FLOWER_CUBE_HEIGHT);
}
